version: '3.8'

services:
  database:
    image: mariadb:latest
    restart: always
    container_name: database
    environment:
      MYSQL_DATABASE: 'shopping-app'  # Default database to create
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'  # Allow empty password for root user
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  # Mount database data to a named volume for persistence
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]

  recipe-api:
    depends_on:
      database:
        condition: service_healthy
    image: team02/recipe-api
    restart: always
    container_name: recipe-api
    environment:
      MYSQL_HOST: database
      MYSQL_PORT: 3306
      MYSQL_DATABASE: shopping-app
      CLOUDINARY_NAME: ${CLOUDINARY_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    ports:
      - "8082:8082"
    volumes:
      - api_data:/app/data  # Mount app data to a named volume for persistence

    frontend:
      depends_on:
        recipe-api:
          condition: service_healthy
      image: team02/frontend
      restart: always
      container_name: recipe-frontend
      environment:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:8082/api
      ports:
        - "3000:3000"

volumes:
  db_data:
  api_data:
