version: '3.8'

services:
  database:
    image: mariadb:latest
    restart: always
    container_name: database
    environment:
      MYSQL_DATABASE: 'shopping-app'  # Default database to create
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'  # Allow empty password for root user
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]

  recipe-api:
    container_name: "recipe-api"
    depends_on:
      database:
        condition: service_healthy
    build:
      context: ../api  # Path to the directory containing the Dockerfile and project files
      dockerfile: docker/Dockerfile  # Path to Dockerfile within the specified context
    restart: always
    environment:
      API_IP: "0.0.0.0"
      API_PORT: "8082"
      MYSQL_HOST: database
      MYSQL_PORT: 3306
      MYSQL_DATABASE: shopping-app
      CLOUDINARY_NAME: 
      CLOUDINARY_API_KEY: 
      CLOUDINARY_API_SECRET: 
    ports:
      - "8082:8082"
    # Volumes are removed here

