spring:
  messages:
    basename: messages
    resources:
      static-locations: classpath:/static/
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true
  mode: DEVELOPMENT
  devtools:
    restart:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:programmentwurf2}?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007
    expiration-time: 3600000

app:
  allowed-origins: http://localhost
  base-url: http://localhost:8080
  application-name: Shopping App
  login-page-url: ${app.base-url}/auth/login
  login-success-url: ${app.base-url}/auth/login-success

cloudinary :
  cloud_name : ${CLOUDINARY_NAME}
  apiKey: ${CLOUDINARY_API_KEY}
  apiSecret : ${CLOUDINARY_API_SECRET}

logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: TRACE
      spring:
        security: DEBUG  # Enable debug logging for Spring Security
      nodeValue: WARN
    blog: WARN

server:
  port: 8082