export enum DishType {
  APPETIZER = 'APPETIZER',
  MAIN_COURSE = 'MAIN_COURSE',
  SIDE_DISH = 'SIDE_DISH',
  DESSERT = 'DESSERT',
  SNACK = 'SNACK',
  BEVERAGE = 'BEVERAGE',
  STREET_FOOD = 'STREET_FOOD',
}
